[project]
name = "parsel_crawler"
version = "0.0.1"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crawlee[parsel]>=0.6.12",
    "apify @ git+https://github.com/apify/apify-sdk-python.git@fix/rq-cache-commit-on-success",
    "certifi<=2025.1.31",
]

