name: Run code checks

on:
  # Trigger code checks on opening a new pull request.
  pull_request:

  # Pushing to the master branch triggers code checks
  push:
    branches:
      - master
    tags-ignore:
      - "**" # Ignore all tags to prevent duplicate checks when tags are pushed.

  # It should also be possible to trigger checks manually
  workflow_dispatch:

jobs:
  lint_check:
    name: Lint check
    uses: apify/workflows/.github/workflows/python_lint_check.yaml@parametrize-python-workflows-by-python-version

  type_check:
    name: Type check
    uses: apify/workflows/.github/workflows/python_type_check.yaml@parametrize-python-workflows-by-python-version
    with:
      python-version: '["3.13"]'
